### ISSUE TITLE
installation ERR on Ubuntu14 (x86)

### ISSUE THREAD

**Issue by wcc21320** [TheThingSystem/steward#296]
Hi, I'm new here and I try to install node-steward on ubuntu 14.04 with node 0.12.13.
After run `$ npm install -l `, I got lots ERR.
First ERR from avahi_pub, which from "git://github.com/TheThingSystem/node_avahi_pub.git"
> avahi_pub/build $ make
>  CXX(target) Release/obj.target/avahi_pub/lib/avahi_pub.o
>../lib/avahi_pub.cc:38:33: fatal error: avahi-client/client.h: no such file or directory
> #include <avahi-client/client.h>
>                                 ^
> compilation terminated.
> make: *** [Release/obj.target/avahi_pub/lib/avahi_pub.o] Error 1

Any suggestion? should I replace it by npm version?

**Comment by mrmakeit** [comment]
Since quite a bit of Steward uses low level libraries, and npm doesn't provide a way to transport pre-compiled modules, you'll need to install the dependincies yourself. I would recommend looking at https://github.com/TheThingSystem/steward/wiki/Bootstrapping-the-Raspberry-Pi#installing-other-dependances which should list the dependencies you need.  For Bluetooth, I would install bluetooth-dev instead of Bluez, since that is the package installed by default.

If you need any help with that, let me know

**Comment by wcc21320** [comment]
Thank you. After apply dependence, I can pass the installation with node 0.10.31 (in twice; first will have ERR messages, so I run the second and seems fine).

**Comment by mrmakeit** [comment]
glad to hear it worked.
